// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLx2r39gFsEqIqH0vvEYZv1OM3If7PUck',
    appId: '1:871815657196:web:8811b4768fa0fc755e17c9',
    messagingSenderId: '871815657196',
    projectId: 'bookfinder-965f7',
    authDomain: 'bookfinder-965f7.firebaseapp.com',
    databaseURL: 'https://bookfinder-965f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookfinder-965f7.firebasestorage.app',
    measurementId: 'G-EFSWH6VYP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHJlheu10Q-sFhhZpdceoVZ4NXsKUH-g',
    appId: '1:871815657196:android:346640e0bce69f715e17c9',
    messagingSenderId: '871815657196',
    projectId: 'bookfinder-965f7',
    databaseURL: 'https://bookfinder-965f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookfinder-965f7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLx2r39gFsEqIqH0vvEYZv1OM3If7PUck',
    appId: '1:871815657196:web:0dab808c8269f4095e17c9',
    messagingSenderId: '871815657196',
    projectId: 'bookfinder-965f7',
    authDomain: 'bookfinder-965f7.firebaseapp.com',
    databaseURL: 'https://bookfinder-965f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookfinder-965f7.firebasestorage.app',
    measurementId: 'G-2Z5Q2WBPCD',
  );
}
