name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  books_finder: ^4.4.0
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.4.1
  talker: ^4.4.1
  talker_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
- assets/images/