name: book_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  books_finder: ^4.4.0
  build_runner: ^2.4.13
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

    
  flutter_application_1: ^0.0.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  go_router: ^14.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  talker_dio_logger: ^4.4.4
  talker_flutter: ^4.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/book.png
